#ifndef YSP_KEYGEN_WASM_H_GENERATED_
#define YSP_KEYGEN_WASM_H_GENERATED_
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

extern void WASM_RT_ADD_PREFIX(init)(void);

/* import: 'wbg' '__wbg_get_9c1840f7ecd81363' */
extern u32 (*Z_wbgZ___wbg_get_9c1840f7ecd81363Z_iii)(u32, u32);
/* import: 'wbg' '__wbindgen_string_get' */
extern void (*Z_wbgZ___wbindgen_string_getZ_vii)(u32, u32);
/* import: 'wbg' '__wbindgen_object_drop_ref' */
extern void (*Z_wbgZ___wbindgen_object_drop_refZ_vi)(u32);

/* export: 'memory' */
extern wasm_rt_memory_t (*WASM_RT_ADD_PREFIX(Z_memory));
/* export: 'get_token_rnd' */
extern void (*WASM_RT_ADD_PREFIX(Z_get_token_rndZ_vi))(u32);
/* export: 'get_signature' */
extern void (*WASM_RT_ADD_PREFIX(Z_get_signatureZ_vi))(u32);
/* export: '__wbindgen_malloc' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___wbindgen_mallocZ_iii))(u32, u32);
/* export: '__wbindgen_realloc' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___wbindgen_reallocZ_iiiii))(u32, u32, u32, u32);
/* export: '__wbindgen_free' */
extern void (*WASM_RT_ADD_PREFIX(Z___wbindgen_freeZ_viii))(u32, u32, u32);
/* export: '__wbindgen_add_to_stack_pointer' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___wbindgen_add_to_stack_pointerZ_ii))(u32);
#ifdef __cplusplus
}
#endif

#endif  /* YSP_KEYGEN_WASM_H_GENERATED_ */
